spring:
  application:
    name: auth
  redis:
    port: ${redis.port}
    host: ${redis.host}
    database: ${redis.default.db}
    pass: ${redis.pass}
    timeout: ${redis.timeout}
    pool:
      max-active: ${redis.maxActive}
      max-idle: ${redis.maxIdle}
      max-wait: ${redis.maxWait}
      testOnBorrow: ${redis.testOnBorrow}
server:
  port: 5001
